apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rag-api
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - "rag-demo.eastus2.cloudapp.azure.com"
      # secretName: tls-cert   # if you have TLS; else remove tls block
  rules:
    - host: rag-demo.eastus2.cloudapp.azure.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rag-api
                port:
                  number: 80

