apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rag-api
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - rag-demo.eastus2.cloudapp.azure.com
      # secretName: tls-cert   # <-- add if you have a TLS secret; otherwise remove the entire tls: section
  rules:
    - host: rag-demo.eastus2.cloudapp.azure.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rag-api
                port:
                  number: 80
