apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rag-api
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts: [ "YOUR-DNS-NAME" ]
      secretName: tls-cert   # created by cert-manager / AGIC / etc.
  rules:
    - host: YOUR-DNS-NAME
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rag-api
                port:
                  number: 80
