apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-prod

resources:
  - ../../base
  - ingress.yaml
  - pdb.yaml
  - networkpolicy.yaml

images:
  - name: ghcr.io/OWNER/REPO
    newName: ghcr.io/OWNER/REPO
    newTag: latest

patches:
  - path: patch-deployment.yaml
