apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rag-api-allow-appgw
  namespace: rag-prod
spec:
  podSelector:
    matchLabels:
      app: rag-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 10.226.0.0/24  # <-- REPLACE with the addressPrefix of appgw-subnet
      ports:
        - protocol: TCP
          port: 80            # Service port (maps to containerPort 8000)
