apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rag-api-allow-all
spec:
  podSelector:
    matchLabels:
      app: rag-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 80
