apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rag-api-allow-from-ingress
spec:
  podSelector:
    matchLabels:
      app: rag-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        # Allow from nginx ingress controller namespace
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        # Allow from same namespace (optional: for sidecars/metrics)
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 80
