apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api
spec:
  replicas: 1
  template:
    spec:
      # nodeSelector:
      #   kubernetes.azure.com/mode: user
      nodeSelector: {}
        kubernetes.io/os: linux
      containers:
        - name: rag-api
          image: ghcr.io/OWNER/REPO:latest   # CI overrides
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: app-config 
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
