# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: rag-api
#   labels:
#     app: rag-api
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: rag-api
#   template:
#     metadata:
#       labels:
#         app: rag-api
#     spec:
#       containers:
#         - name: rag-api
#           image: ghcr.io/OWNER/REPO:latest  # kustomize will override
#           imagePullPolicy: IfNotPresent
#           ports:
#             - containerPort: 8000
#           readinessProbe:
#             httpGet:
#               path: /docs    # returns 200 if FastAPI is up
#               port: 8000
#               scheme: HTTP
#             initialDelaySeconds: 5
#             periodSeconds: 10
#             timeoutSeconds: 3
#             failureThreshold: 6
#           livenessProbe:
#             httpGet:
#               path: /docs
#               port: 8000
#               scheme: HTTP
#             initialDelaySeconds: 20
#             periodSeconds: 20
#             timeoutSeconds: 3
#             failureThreshold: 5
#           resources:
#             requests:
#               cpu: 100m
#               memory: 256Mi
#             limits:
#               cpu: 500m
#               memory: 512Mi

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-api
  template:
    metadata:
      labels:
        app: rag-api
    spec:
      containers:
        - name: rag-api
          image: ghcr.io/OWNER/REPO:latest
          imagePullPolicy: Always     # <-- add this
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          # envFrom / probes as you already have


