apiVersion: v1
kind: Service
metadata:
  name: rag-api
  labels:
    app: rag-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: rag-api
  ports:
    - name: http
      port: 80
      targetPort: 8000


